### ISSUE TITLE
Support more emulated audio types

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/SidWizPlus#16]
It would be good to support more than VGM, including:

* multi track files (NSF, SID)
* different types of metadata

I should probably make this an interface so it's easy to extend (and hope for pull requests). Or maybe Multidumper can dump tags to a uniform format for me?

**Comment by maxim-zhao** [comment]
It can indeed - just run with --json to see the metadata (including "subsong count").

**Comment by Supremeoverlord3** [comment]
Whenever I try to play a file such as an .nsf file, it says that it is checking the file and is stuck loading it.  Can this issue be resolved?

**Comment by maxim-zhao** [comment]
This feature is reliant on MultiDumper which may have some inconsistent behaviour between versions. The "checking" phase is where it runs `multidumper.exe --json <filename>` - what do you get if you run that in a console?

**Comment by Supremeoverlord3** [comment]
It says that it is checking the file and stays there without doing anything else.

**Comment by maxim-zhao** [comment]
Yes, but that's probably because your multidumper isn't working as it should. Can you tell me where you got it from, and try the command I mentioned above? I can load NSF files fine.

**Comment by Supremeoverlord3** [comment]
I got the GUI version from AppVeyor.  Thank you so much for your help; I really want to see things in oscilloscope view.

**Comment by maxim-zhao** [comment]
To support emulated audio files, SidWizPlus uses another program called "multidumper". It prompts you to locate it when you first use it; if you want to edit the path then you can edit a file at `"C:\Users\<your username>\AppData\Roaming\SidWizPlus\settings.json"` (or just delete it to be re-prompted). Unfortunately it is tricky to get hold of multidumper builds. I've uploaded one here: https://github.com/maxim-zhao/SidWizPlus/releases/tag/multidumper

**Comment by Supremeoverlord3** [comment]
Wow! I can see it now. Unfortunately, I can't hear anything and can't control the playback; it is frozen showing the waveforms. I can move a bar on the bottom and it shows the waveforms changing but there is no sound and I cannot play the file.

**Comment by maxim-zhao** [comment]
You're not supposed to hear anything, that's a preview. Go to the video tab and render it using ffmpeg.

**Comment by Supremeoverlord3** [comment]
Okay, I rendered it, but it is still showing preview. Where is the full file?

**Comment by StinkerB06** [comment]
> Okay, I rendered it, but it is still showing preview. Where is the full file?

It should be located in the directory you had saved it to.

**Comment by Supremeoverlord3** [comment]
They are all just separate channels and no visual.

**Comment by maxim-zhao** [comment]
Check the ffmpeg enabled button and try again. Make sure you have ffmpeg.

**Comment by Supremeoverlord3** [comment]
I got it working! Thank you so much for your help. I really appreciate being able to do this.

**Comment by Supremeoverlord3** [comment]
I would also like to put in a request that formats such as .minigsf are supported in future builds.

**Comment by maxim-zhao** [comment]
I'm limited to what Multidumper supports. I'm not sure that format will split to sensible channels anyway.
