### ISSUE TITLE
I thought this program only outputted master audio

### ISSUE THREAD

**Issue by StinkerB06** [maxim-zhao/SidWizPlus#28]
Instead of outputting only the master audio, it mixes my oscilloscope channels and master audio into the video. In the case of SidWiz2 and Zeinok's OVGen, they output master audio only.

Since I generated the audio files from OpenMPT, the master audio export causes an echo effect.

**Comment by maxim-zhao** [comment]
I probably never tested that as I always use the mixed audio. Should be easy to fix.

It's probably a bug in OpenMPT if the mixed audio has a delay compared to unmixed.

**Comment by StinkerB06** [comment]
Oh! I figured out why: I had "Autogenerate master audio file" turned on and had the Location set as well.
