### ISSUE TITLE
Triggering direction option

### ISSUE THREAD

**Issue by acrouzet** [maxim-zhao/SidWizPlus#37]
The waveform triggering currently goes in the negative (down) direction (this is the opposite from previous builds as the current build inverts the waveforms for some reason). It would be useful to have an option for which direction the triggering goes, as certain waveforms trigger better in one direction than the other.

**Comment by maxim-zhao** [comment]
It was actually just rendering upside down.

You can achieve the desired effect by applying a negative scale factor to the waves:
![image](https://user-images.githubusercontent.com/7792986/52920843-0ac64900-3309-11e9-93f3-6320ec00cb78.png)
![image](https://user-images.githubusercontent.com/7792986/52920850-174aa180-3309-11e9-8362-e099e9c77c00.png)
Would it be useful to be able to do this without rendering the wave inverted?

**Comment by acrouzet** [comment]
It would be.
