### ISSUE TITLE
Error message in channels when importing long audio files

### ISSUE THREAD

**Issue by acrouzet** [maxim-zhao/SidWizPlus#44]
![Capture](https://user-images.githubusercontent.com/47704566/54730700-acd38e00-4b60-11e9-9000-8f602c86d934.PNG)

For the record, the audio files I used were around 1 hour, 10 minutes, and 30 seconds long. Changing sample rate did not seem to solve the issue.

**Comment by maxim-zhao** [comment]
That's... nuts :) it's exceeding 2 billion samples. Should be easy to fix, but I'll need to generate some long files first.
