### ISSUE TITLE
FFMPEG is freezing after frame 1423

### ISSUE THREAD

**Issue by StinkerB06** [maxim-zhao/SidWizPlus#46]
After rendering about 1423 frames of video at 60 FPS (~23.717 seconds), FFMPEG stops rendering frames completely. The `SidWiz.exe` task consumes ~40% CPU, while the newest vanilla FFMPEG static build for 64-bit Windows drops to near 0%. I'm on Windows 10 x64, OS version 10.0.16299.1087.

The video I was rendering contains 9 channels, 3 columns, grid borders, wave fills, changed label position/font, and auto-correlation trigger with look-ahead.

Here's the ZIP file containing the WAV's and the *.sidwizplus.json:
https://www.dropbox.com/s/cdy59323spptq2y/SidWizPlus%20Frame-1423%20bug.zip?dl=0
After downloading and extracting, in any JSON editor, change all `"Filename"` values and the `"Path"` value to the directories that the WAV's were extracted to. Also, change all `"LabelFont"` values to a font you have on your PC.

**Comment by maxim-zhao** [comment]
The autocorrelation trigger is very much in alpha and is not expected to work.

**Comment by StinkerB06** [comment]
Thanks! My bad for not reading the wiki page!
