### ISSUE TITLE
Possible Issue: Noise not rendering properly

### ISSUE THREAD

**Issue by Supremeoverlord3** [maxim-zhao/SidWizPlus#51]
For 'Holders of Power', Ys: The Vanished Omens (PC88), the channel used for noise is barely loud enough to hear.

**Comment by maxim-zhao** [comment]
That's an issue with whatever is dumping the file to disk, not me. I'm guessing you dumped it with multidumper?

**Comment by Supremeoverlord3** [comment]
Yes. I suspected that might be the case, which is why I said 'Possible issue'; are there any other dumpers available?

**Comment by maxim-zhao** [comment]
Yes, there are many but I can't comment on all of them. You need a combination of:
- ability to dump to wav
- ability to mute all channels except one
Multidumper exists to make this easy to do from the command line, but of course there are different opinions on the best way to do things. I think you can do this with vgmplay but it requires editing the ini file for each channel, you can also do it interactively in Winamp and in_vgm.

**Comment by Supremeoverlord3** [comment]
Hmm; I'll have to research it a little. Thank you for your help! Developers like you really make it great to be interested in retro gaming.
