### ISSUE TITLE
exported mp4 file looks corrupted

### ISSUE THREAD

**Issue by YouCantPronounceKazotsky** [maxim-zhao/SidWizPlus#54]
attempted to render with default ffmpeg parameters and the mp4 looked like this

![image](https://user-images.githubusercontent.com/40926602/85238402-a7b45d00-b3fb-11ea-8c88-840b651822d0.png)

**Comment by maxim-zhao** [comment]
Looks bad, but I can't reproduce it. Possibly an issue with your decoder?

**Comment by YouCantPronounceKazotsky** [comment]
at this point i assume its something to do with ffmpeg because it also happened with corrscope
