### ISSUE TITLE
Multidumper not dumping the entire NSF track

### ISSUE THREAD

**Issue by OmerFlame** [maxim-zhao/SidWizPlus#55]
I have a 5-minute NSF that I want to dump, but it's only dumping 3 minutes and 8 seconds.

How can I fix this?

The NSF file is in this Google Drive link.

[NSF HERE](https://drive.google.com/file/d/19l3XPzpSCtIGV3_8ker0Djs26yVfhrLZ/view?usp=sharingl)

**Comment by maxim-zhao** [comment]
NSFs often don't have the track timing information encoded, and I guess Multidumper is defaulting here. It seems you can use tools to edit the metadata (e.g. using foo_gep in fb2k), but I'm not familiar. Multidumper isn't my tool so I can't really help with it.
