### ISSUE TITLE
Do not render 'This channel is silent'

### ISSUE THREAD

**Issue by stefandrissen** [maxim-zhao/SidWizPlus#57]
I've generated quite some oscilloscope videos for SAM Coupé tunes. The SAM Coupé uses a Philips SAA1099 sound chip which has six stereo channels. When rendering, I split the channels into left and right components, showing left on the left and right on the right.

Sometimes the left or right component of a channel is silent. This is indicated with 'This channel is silent', which is fine. 
If both left and right are silent I will remove them both. But when only left or right is silent I would like to keep both sides in for balance.

Unfortunately the 'This channel is silent' message is also rendered into the video, see for example:

https://www.youtube.com/watch?v=nkpzhIunJHY

Can that channel be presented as a zero amplitude line instead?

**Comment by maxim-zhao** [comment]
You can manually replace them with a blank channel but it's not exactly user-friendly :) Have a try with build 124 which adds a RenderIfSilent option to each channel:
![image](https://user-images.githubusercontent.com/7792986/110385907-76e28980-8057-11eb-8465-1f0524391ea7.png)

**Comment by stefandrissen** [comment]
Nice! That was quick! :-)
