### ISSUE TITLE
Add External Trigger feature

### ISSUE THREAD

**Issue by Soundshock** [maxim-zhao/SidWizPlus#58]
AKA two .wavs for one channel. OVGen supported this and it's really powerful - with some hex editing some VGMs can produce both the regular waveform along with a basic waveform for a 100% perfect track,

**Comment by maxim-zhao** [comment]
I don't much like it myself - I'd rather have the trigger algorithms work better - but I may as well add it :)

Please try this in https://github.com/maxim-zhao/SidWizPlus/releases/tag/126:

![image](https://user-images.githubusercontent.com/7792986/111084771-fff03980-850b-11eb-93ca-9a9fe0908b3f.png)

and let me know if it works. Note that it will follow the Side and HighPassFilter settings of the sound channel.

**Comment by Soundshock** [comment]
It's beautiful!! First test https://www.youtube.com/watch?v=M5zDPaQfBC8
So far I've only broke the vgm by hand in a hex editor to get a good external trigger but it should be possible to automate I'll keep working on that

**Comment by maxim-zhao** [comment]
Cool :) There is the beginnings of a VGM parsing lib in this project, so far used to extract GD3s and YM2413 instrument usage, which may be useful for you if C# is your thing.
