### ISSUE TITLE
Don't read silent External Trigger when actual Audiable Track is Silent

### ISSUE THREAD

**Issue by FlygonAU** [maxim-zhao/SidWizPlus#65]
https://cdn.discordapp.com/attachments/327805534793105411/851133376101482558/unknown.png
For some visual reference.

The top audio file is the External Trigger clock, and the bottom audio file is the actual audio/what is being seen by the viewer.

The External Trigger having a set clock whilst the audio is actually silent is causing some really really bad visual bugs that are unfixable unless you outright don't use the External Trigger, or manually mute the sections of the clock actually causing issues.
Visually, the timbre winds up not locking onto its actual pitch at all, but rather into the sections outside of the audiable range to the 'left' and 'right' of the track.

**Comment by maxim-zhao** [comment]
![image](https://user-images.githubusercontent.com/7792986/120933648-f03f5600-c6f2-11eb-91b3-fdce1e249916.png)

**Comment by maxim-zhao** [comment]
Hmm, odd - it ought to render the silence according to the trigger point anyway. I'll have to experiment a bit.

**Comment by maxim-zhao** [comment]
Fixed by 5fa0c03e20da241c89fb09241003996b1a083b12
