### ISSUE TITLE
Default Settings for New Channels Added from Blank

### ISSUE THREAD

**Issue by FlygonAU** [maxim-zhao/SidWizPlus#67]
With hindsight, this is something I've been really needing for a good while.

When adding new tracks from blank into SidWizPlus, it uses really inconvenient default settings that I need to change every time.
I was hoping to request some method of having a "User Preset" for any new channels added into SidWizPlus, ie. letting you define as part of the default settings what adding any new channel to any SidWizPlus instance has.

This'd be useful for me, because when I remove all channels after SidWizPlus has finished printing something out, it's a nuisance to have to define all the settings again as I add the new .wav's, and it's super easy to overlook a setting and only fully find out when I've finished printing the track out, and have to redo the printout again with the corrected settings.
This will also make juggling 4-8 SidWizPlus instances at once a lot easier.

**Comment by maxim-zhao** [comment]
I guess I could add a button to "save as default channel settings" and then apply those to new channels appearing in future?

**Comment by FlygonAU** [comment]
Yeah, that's pretty much exactly what I was thinking. And to apply to any other SidWizPlus sessions too.

**Comment by maxim-zhao** [comment]
A bit harder to do cross-session. Notice the copy/paste settings buttons which do something similar; but it would be weird to use the clipboard as the source for the defaults.

**Comment by FlygonAU** [comment]
I meant as in saving it inside the AppData file that SidWizPlus stores its other settings inside.

**Comment by maxim-zhao** [comment]
Sure, and that's how I'd do it for the saving - but currently the config file is written on exit, so changes only affect new instances after you exit. Making it written "live" and monitored by other instances requires a little more effort.
