### ISSUE TITLE
cant change channel options

### ISSUE THREAD

**Issue by FlashlightET** [maxim-zhao/SidWizPlus#68]
![image](https://user-images.githubusercontent.com/29938499/124386946-c3a73b80-dcaa-11eb-8b70-5d0b674bb602.png)
it showed the first time i ever booted the gui, then when i clicked a tab and clicked back it never showed the channel options ever again.

video example: https://user-images.githubusercontent.com/29938499/124387482-e0dd0980-dcac-11eb-94d2-ddb73f149310.mp4

**Comment by maxim-zhao** [comment]
What happens if you click on one of the channels?

**Comment by FlashlightET** [comment]
Holy crap.
