### ISSUE TITLE
Build Not Available?

### ISSUE THREAD

**Issue by 48lexR** [maxim-zhao/SidWizPlus#77]
Hey there!

I'm looking to get into oscilloscope visualizations, but I'm having some difficulty running SidWizPlus. After downloading the GitHub zip, I realized I wasn't going to be able to run it, and the appveyor site won't let me download the build. It says that items in the archive are deleted after a certain period of time. I'm not sure what to do. I've already downloaded FFMPEG and Multidumper, so the only other step should be downloading and running SidWizPlus, right?

Thanks so much in advance!

**Comment by R4to0** [comment]
It should be at releases section, you can download both command line and gui executables (zip archives).

https://github.com/maxim-zhao/SidWizPlus/releases/latest

**Comment by maxim-zhao** [comment]
That's right. I've updated the readme to match.
