### ISSUE TITLE
sidplayfp expects output filename without ".wav" suffix

### ISSUE THREAD

**Issue by TakuikaNinja** [maxim-zhao/SidWizPlus#78]
Currently SidWizPlus calls sidplayfp with the output filename parameter "{song.File.Filename} - Song {song.Index} - {song.File.Chip} #{channel}.wav" for recording from SID files. However, sidplayfp add an extra ".wav" suffix because it expects the filename to have no suffix. 
This results in the audio files being called "{song.File.Filename} - Song {song.Index} - {song.File.Chip} #{channel}.wav.wav", which is not what the program is looking for.

**Comment by maxim-zhao** [comment]
Hmm, I'm sure it worked when I used it last - did sidplayfp change? [The docs say](https://github.com/libsidplayfp/sidplayfp/wiki/sidplayfp):

> `<name>` IS NOT checked for or appended with a legal wav file extension.

I'll try again with the latest version...

**Comment by maxim-zhao** [comment]
See also https://github.com/libsidplayfp/sidplayfp/issues/10
