### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by SpiritAxolotl** [maxim-zhao/SidWizPlus#81]
I'm currently trying to mimic SidWizPlus's oscilloscope view in Blender so I can add shaders and/or effects to the waveform, but I cannot find any information documenting the behavior of the waveform (all I can get right now is a pure sinewave based on the current point in the song).
Any information is appreciated!

**Comment by maxim-zhao** [comment]
It's open source and well commented. Have a look in https://github.com/maxim-zhao/SidWizPlus/tree/master/LibSidWiz/Triggers. There are multiple algorithms that effectively take the waveform and try to pick the "trigger" point, for example the "biggest positive wave area" looks for areas where the wave is positive, sums the values and picks the largest in the window.
