### ISSUE TITLE
sidwizplusgui: load settings via command line

### ISSUE THREAD

**Issue by stefandrissen** [maxim-zhao/SidWizPlus#84]
I have a json settings file that I load when I start sidwizplusgui.

I had a quick look at using the command line sidwizplus, while that provides a lot of options, it does not seem to allow setting label settings per channel, only a default for all channels.

As a compromise to adding per channel settings to the command line version, maybe it would be possible to allow providing a settings file to sidwizplusgui?

**Comment by maxim-zhao** [comment]
The command line one is very much tailored to my specific needs and nested config is quite hard to do on a command line. However, making the JSON loadable across the versions should be trivial, and making the GUI take it on the command line works the same.
