### ISSUE TITLE
Rendering 8x slower with version 193

### ISSUE THREAD

**Issue by stefandrissen** [maxim-zhao/SidWizPlus#85]
I updated to the latest version (193 | 2023-09-17) today and noticed that the rendering time has increased **dramatically**. I was using an older 2022-09-28 (not sure where these dates are coming from) version.

After 10%, the ETA on the same source files:

193: 1 hour 20 minutes
192: 10 minutes
191: 10 minutes

![image](https://github.com/maxim-zhao/SidWizPlus/assets/5297464/0f49a29e-f5c5-4ca5-a1ce-8c5612674ecd)
![image](https://github.com/maxim-zhao/SidWizPlus/assets/5297464/8681f0d7-4042-4199-aa66-633bbd1b727e)

I am using a 4 core HT PC - with version 193 all 8 logical cores are near 100%.

I am using wav files as input.

**Comment by maxim-zhao** [comment]
The speed was the same but there was a logic error that caused it to render way more frames than there was data. This was a mistake introduced when I added support for MP3s as sources. It should be better in v194.
