### ISSUE TITLE
ffmpeg: Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)

### ISSUE THREAD

**Issue by stefandrissen** [maxim-zhao/SidWizPlus#86]
I am rendering mkv with 60 fps, ffmpeg displays the warning in title:

````
Output #0, matroska, to 'D:\retro\sidwizplus\output\Interphace - Peace Droid.mkv':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264) (H264 / 0x34363248), yuv444p(progressive), 3840x2160, q=-1--1, 60 fps, 1k tbn, 60 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:1: Audio: vorbis (libvorbis) (oV[0][0] / 0x566F), 44100 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.91.100 libvorbis
[rawvideo @ 00000176f27b0480] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
frame=10965 fps= 22 q=31.0 size=  118016kB time=00:03:01.76 bitrate=5318.8kbits/s speed=0.361x
````

Based on [this answer](https://video.stackexchange.com/questions/25643/ffmpeg-thread-queue-size-warning-what-does-this-mean) on video.stackexchange.com I am guessing that this also applies to how SidWizPlus is calling ffmpeg with [-framerate](https://github.com/maxim-zhao/SidWizPlus/blob/bdc17dbff8ba81d1957e707a6517d24935dad53c/LibSidWiz/Outputs/FfmpegOutput.cs#L29C88-L29C98).

Instead of using ``-framerate`` you should be using ``-r`` ?

**Comment by maxim-zhao** [comment]
There's comments on that answer saying it's wrong, but to be honest I'm not sure. I thought it meant that ffmpeg was failing to encode as fast as the data is coming in, so the pipe is getting blocked. I guess I'll experiment to see if it makes any difference; it's certainly not causing any frames to be dropped and I don't think encoding speed is affected.
