### ISSUE TITLE
release 198: insufficient resources

### ISSUE THREAD

**Issue by stefandrissen** [maxim-zhao/SidWizPlus#87]
I just download release 198 to see the effect of the ffmpeg parameter changes.

Unfortunately, rendering a video crashes out with "Insufficient resources", a set of errors flashed by in the ffmpeg console. I was able to get a screenshot of task manager, notice the memory going down before the crash:

![image](https://github.com/maxim-zhao/SidWizPlus/assets/5297464/e2a4c66b-f2c3-4c18-ac47-b4d979c6dd7a)

The GUI is still alive and I can restart it, but it just crashed again, this time I managed to capture the console just before it disappeared:

![image](https://github.com/maxim-zhao/SidWizPlus/assets/5297464/018d9437-d05e-418c-b251-5ca63fc0fd33)

**Comment by maxim-zhao** [comment]
That's kind of what I feared - this is just increasing a buffer in Ffmpeg and now it's too big if you are using a high resolution and/or a 32-bit Ffmpeg (maybe). I may just have to remove it again...
